export const GET_CURRENCIES_START = "GET_CURRENCIES_START";
export const GET_CURRENCIES_SUCCESS = "GET_CURRENCIES_SUCCESS";
export const GET_CURRENCIES_FAILURE = "GET_CURRENCIES_FAILURE";
export const CONVERT_START = "CONVERT_START";
export const CONVERT_SUCCESS = "CONVERT_SUCCESS";
export const CONVERT_FAILURE = "CONVERT_FAILURE";
